theme = "tokyonight_storm"

[editor]
line-number = "relative"
mouse = true
scrolloff = 20
bufferline = "multiple"

[editor.cursor-shape]
select = "underline"

[keys.normal]
"C-." = ":bn"
"C-," = ":bp"
"esc" = ["collapse_selection", "keep_primary_selection"]
"X" = "extend_line_above"
"C-n" = ":open"
"C-q" = ":bc"
"C-/" = ["toggle_comments"]
"C-R" = ":config-reload"
"A-f" = ":format"